name: motor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  get: any
  responsive_sizer: any
  flutter_svg: any
  cloud_firestore: any
  cloud_firestore_web: any
  firebase_auth: any
  firebase_auth_web: any
  firebase_core: any
  firebase_core_web: any
  universal_html: any
  restart_app: any
  pdf: any
  printing: any
  html: any
  http: any
  intl: any
  fl_chart: any
  dropdown_search: any
  google_fonts: any
  typed_data: any
  syncfusion_flutter_pdf: any
  excel: any
  path_provider: any
  permission_handler: any
  syncfusion_flutter_xlsio: any
  open_file: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Angkor
      fonts:
        - asset: assets/fonts/Angkor-Regular.ttf

    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKhmer-Light.ttf
          weight: 300

    - family: KhmerFont
      fonts:
        - asset: assets/fonts/Khmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/KhmerOS.ttf
          weight: 400
        - asset: assets/fonts/KhmerOS_original.ttf
          weight: 700

    - family: Koulen
      fonts:
        - asset: assets/fonts/Koulen-Regular.ttf
