// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDolAgNTnb0rLK5SKJWdSofO6wnmcS5qsg',
    appId: '1:597512006190:web:03ecd6d687563418704dbf',
    messagingSenderId: '597512006190',
    projectId: 'motorproject-278f0',
    authDomain: 'motorproject-278f0.firebaseapp.com',
    storageBucket: 'motorproject-278f0.appspot.com',
    measurementId: 'G-X52MP3NB4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00oKQKhAyF2uPJkLz44hIzwKj_8dvKc0',
    appId: '1:597512006190:android:4d80457b6bc63bc7704dbf',
    messagingSenderId: '597512006190',
    projectId: 'motorproject-278f0',
    storageBucket: 'motorproject-278f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EOyeqoVfyxzkKWCWrOdnLZWM6ezc6w4',
    appId: '1:597512006190:ios:641c1fd6b9150ced704dbf',
    messagingSenderId: '597512006190',
    projectId: 'motorproject-278f0',
    storageBucket: 'motorproject-278f0.appspot.com',
    iosBundleId: 'com.example.motor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_EOyeqoVfyxzkKWCWrOdnLZWM6ezc6w4',
    appId: '1:597512006190:ios:641c1fd6b9150ced704dbf',
    messagingSenderId: '597512006190',
    projectId: 'motorproject-278f0',
    storageBucket: 'motorproject-278f0.appspot.com',
    iosBundleId: 'com.example.motor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDolAgNTnb0rLK5SKJWdSofO6wnmcS5qsg',
    appId: '1:597512006190:web:06a2e84c7268c078704dbf',
    messagingSenderId: '597512006190',
    projectId: 'motorproject-278f0',
    authDomain: 'motorproject-278f0.firebaseapp.com',
    storageBucket: 'motorproject-278f0.appspot.com',
    measurementId: 'G-E8Y5FH7F0N',
  );
}
